import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactQueryProvider } from "@/providers/react-query-provider";
import { LogoutListener } from "@/components/listeners/logout-listener";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Finance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}>
        <ReactQueryProvider>
          {children}
          <Toaster 
            richColors
            position="top-right"
            toastOptions={{
              duration: 5000
            }}  
          />
          <LogoutListener />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
